Incubo4u/add-more-tests
jellyfish-dev/react-native-client-sdk pull request #26
Opened 2024-01-08 16:25 UTC by incubo4u

2024-01-09 18:01 UTC, karkakol commented on package.json
> +    "@types/react": "^18.2.6",
💢 
pls fixed versions of react, react type , react dom etc

2024-01-09 19:05 UTC, incubo4u commented on example/contexts/JellyfishExampleContext.tsx
> +type VideoRoomState = 'BeforeMeeting' | 'InMeeting' | 'AfterMeeting';
rn membrane use it only in the videoroomContext is not available

2024-01-10 17:41 UTC, karkakol requested changes

2024-01-10 18:20 UTC, karkakol approved these changes

2024-01-10 18:24 UTC, merged