Prevent camera toggle on iOS simulator
jellyfish-dev/react-native-client-sdk pull request #43
Opened 2024-04-11 16:09 UTC by balins

## Description
This PR adds a toast message informing the user that camera won't work on iOS simulator.

## Motivation and Context
With the current implementation it's not clear why the camera toggle doesn't work.

## How has this been tested?
Tested on iOS simulator that the toast pops up and the toggle is permanently set to off state.

## Types of changes
Just a change in the example app, doesn't affect the SDK.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Screenshots (if appropriate)
<img width="783" alt="Screenshot 2024-04-11 at 18 08 41" src="https://github.com/jellyfish-dev/react-native-client-sdk/assets/31112335/d9d779c1-1996-4f4f-ad83-1f3d7d548dbf">

2024-04-12 12:00 UTC, karkakol requested changes

2024-04-15 07:37 UTC, balins commented on example/contexts/JellyfishExampleContext.tsx
> +  }, [isCameraOn, membraneToggleCamera, videoRoomState, isIosEmulator]);
Yeah, it was a linter issue. But on second thought, seems like `isIosEmulator` should defined outside of the component as its constant between re-renders. This way we can remove the dependency in the hook.

2024-04-15 08:37 UTC, karkakol approved these changes
💪

2024-04-15 09:29 UTC, merged

2024-04-15 11:40 UTC, mironiasty commented on example/contexts/JellyfishExampleContext.tsx
> +const isIosEmulator = Platform.OS === 'ios' && !Device.isDevice;
nit: `isIosSimulator` (there is small difference between emulators and simulators)